# development:
#   adapter: postgresql
#   database: ar-ex_dev
#   encoding: unicode
#   host: localhost

# production:
#   adapter: postgresql
#   database: ar-ex_prod
#   encoding: unicode
#   host: localhost

development:
  adapter: postgresql
  database: HMMC_dev
  encoding: unicode
  host: localhost

production:
  adapter: postgresql
  database: HMMC_prod
  encoding: unicode
  host: localhost
